# Generated by Django 4.1.4 on 2022-12-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.CharField(
                        default="02833e3e-9727-4ba3-8e15-cd25236c1662",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(
                        default="a4966541-b3eb-42a4-b36f-d499551385df",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("preparing", "preparing"),
                            ("shipping", "shipping"),
                            ("delivered", "delivered"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        default="b3ddc8e1-2f4a-4130-8953-e25902cdf8d3",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(
                        default="a32e84f4-b67f-4265-832c-ebab199ab596",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_desc", models.TextField()),
                ("qty", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("old_price", models.FloatField()),
                ("new_price", models.FloatField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yadawy.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "detail_id",
                    models.CharField(
                        default="c72c4892-0348-4cc6-9d70-d2639f549cb9",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qty", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="yadawy.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="yadawy.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="details",
            field=models.ManyToManyField(
                related_name="details",
                through="yadawy.OrderDetail",
                to="yadawy.product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="yadawy.user"
            ),
        ),
    ]
