# Generated by Django 4.1.4 on 2022-12-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yadawy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.CharField(
                default="9b8657ea-c37b-49da-bb5d-7b0a35733c9b",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="ad327f50-006c-4ccb-ab52-6de79bbf0872",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="detail_id",
            field=models.CharField(
                default="6ce883db-4087-452e-be81-3ac1b86fa1b7",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(
                default="63dc6a08-5b6c-4140-8523-1e3c623a4eb0",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default="5572161b-76b5-4bc1-961b-dfe00c5f81cd",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
