# Generated by Django 4.1.4 on 2022-12-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yadawy", "0002_alter_category_category_id_alter_order_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.CharField(
                default="85fe353f-b65c-4f5f-97ee-f8afcb0b3873",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="e72fd978-51fb-4f52-9184-6c5908b0203e",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="detail_id",
            field=models.CharField(
                default="34b30598-29cd-46af-a6e0-7608fb9e4e48",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(
                default="91aaf71c-34e5-41ca-8015-52cbb54ee203",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default="750b1db0-8c40-4c34-8e21-cc30314944b2",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
